---
# Create a security group for an EC2 instance:
# Inbound - Your IP address (SSH, HTTP); Ansible IP address (SSH)
# Outbound – HTTPS & HTTP to any IP address

- name: create security group
  ec2_group:
    name: "{{ security_group_name }}"
    description: sg with rule descriptions
    vpc_id: "{{ aws_vpc_id }}"
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        cidr_ip: "{{ home_ip }}"
        rule_desc: Inbound - Your IP address (HTTP)
      - proto: tcp
        ports:
        - 22
        cidr_ip:  "{{ home_ip }}"
        rule_desc: Inbound - Your IP address (SSH)
      - proto: tcp
        ports:
        - 22
        cidr_ip:  "{{ ansible_ip }}"
        rule_desc: Inbound - Ansible IP address (SSH)  
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
